### ISSUE TITLE
admin111的password

### ISSUE THREAD

**Issue by Tonkong** [yiifans/lulucms2#3]
hi ~
后台管理admin111的密码是多少啊~ 输入admin111进去不啊~

**Comment by huasxin** [comment]
我的办法：

1、phpmyadmin进入数据库，点击lulucms2，切换到users表里，可以见到admin、demo等用户列表；
2、编辑demo属性，设置demo权限为admin；
3、后台进入，使用demo/demo，这是可以新添加用户；
4、新建admin用户名，设置密码；
5、可以考虑删除admin111.

祝顺利！

Original Message
Sender:Tonkongnotifications@github.com
Recipient:yiifans/lulucms2lulucms2@noreply.github.com
Date:Thursday, Aug 6, 2015 11:27
Subject:[lulucms2] admin111的password (#3)

hi ~
 后台管理admin111的密码是多少啊~ 输入admin111进去不啊~

**Comment by Tonkong** [comment]
谢谢了，研究半天不如这里问下master
Thank you ~

**Comment by yiifans** [comment]
嗯，可以那样解决。
过几天会更新sql脚本，把密码重新设置一下

打开数据库，直接在数据库里面复制demo的密码，然后修改admin111的密码。
这样admin111的密码就是demo了
